# Stage 1: Builder
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Оптимизация кеширования: сначала файлы модулей
COPY go.mod go.sum ./
RUN go mod download

# Затем исходный код
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o producer ./cmd/producer/main.go

# Stage 2: Runtime
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/producer .

EXPOSE 8080
CMD ["./producer"]